name: Lint

on:
  push:
    branches: 
      - master
      - develop

  pull_request:
    branches: 
      - master
      - develop

jobs:
  golang-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        cache: false
        go-version: 1.20.x
        
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        # In order:
        # * Module download cache
        # * Build cache (Linux)
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - run: |
        go mod download

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
        version: v1.50
        working-directory: ./
        skip-pkg-cache: true
        skip-cache: true
        skip-build-cache: true
        args: --timeout=99m --config ./.golangci.yml
